# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: test ci

on:
  push:
    branches:
      - master

jobs: #liste des jobs
  build: #id du job
    name: #nom du job
    runs-on: choix de l'executeur (image docker, serveur dédié, ...)
    steps: # liste des steps à executer
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean compile